### ISSUE TITLE
Failure response from the api are cached, and then are not retried

### ISSUE THREAD

**Issue by ceddlyburge** [ceddlyburge/elm-league-tables-from-google-sheets#10]
The failure from a http request is cached in the model, so when navigating to top scorers, results / fixtures or league tables you might immediately get the failure screen. It should try another http request at this point. 

The problem is that we just check if there is an item in the dictionary, but we don't check if the relevant entry contains a success or a failure response.

This happens for the top scorers, results / fixtures and the league table, and is controlled by `leagues : Dict String (WebData League)` in the model.

**Comment by humayuntanwar** [comment]
hello i would like you help with this issue, can you provide any other relevant info that i can use to solve this?

**Comment by ceddlyburge** [comment]
Sure! Are you familiar with the Elm programming language (which is what this is written in)?

If you look at `Model.elm` there is the `Model` type alias, which has a `leagues` property, which is a `Dict String (WebData League)`.

In `UpdateHelpers.elm`, line 20, this Dict is checked to see if contains anything for the passed `leagueTitle`. If there is no entry in the Dict, it calls the Api to get one, whereas if there is an entry it just returns this.

The problem is that the entry in the Dict might be saving a failed response from the Api (a timeout or something), so as well as checking to see if an Entry exists, we should also check if the entry is `RemoteData.Failure`, and if so also call the api.

The tests for this are in `UpdateHelpersTest.elm`, and it would be good to add a new test (and probably fix up and existing one) for this new functionality.

Cheers, Cedd
